[package]
name = "SqliteCleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
rusqlite = "0.32.1"
once_cell = "1.20.2"
serial_test = "3.2.0"

[profile.dev]
incremental = true # Compile your binary in smaller steps.
codegen-units = 20 # Compile your binary in smaller steps. The higher the number, the faster the compilation. The lower the number, the smaller the binary size.
opt-level = 0 # Prioritizes fast compilation.
panic = "unwind" # Allows for better debugging.
debug = true # Enables debug symbols.
lto = false # Disables link-time optimization, which speeds up compilation.


[profile.release]
codegen-units = 1
opt-level = 2
panic  = "abort"
strip = true
debug = false
lto = true
